name: Deploy to Google Cloud VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.VM_PORT }} ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          set -e

          echo "Starting deployment..."
          cd ~/proj

          echo "Pulling latest code..."
          git pull origin main

          echo "Building and restarting containers..."
          docker-compose down
          docker-compose build
          docker-compose up -d

          echo "Deployment completed successfully!"
          EOL
          
          scp -P ${{ secrets.VM_PORT }} deploy.sh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/
          ssh -p ${{ secrets.VM_PORT }} ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "chmod +x ~/deploy.sh && ~/deploy.sh"