name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0

      - name: Install frontend dependencies
        working-directory: spotify-analyzer
        run: npm install
    
      - name: Build with Maven
        working-directory: backend
        run: mvn clean install -DskipTests

      - name: Start Spring Boot application
        working-directory: backend
        run: |
          nohup mvn spring-boot:run &

      - name: Wait for Spring Boot app to be ready
        working-directory: backend
        run: |
          echo "Waiting for Spring Boot app to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "Spring Boot app is up!"
              break
            fi
            echo "Still waiting... ($i)"
            sleep 2
          done

      - name: Start Python microservice
        working-directory: py-microservice
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          python main.py &

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "Backend is up!"
              break
            fi
            echo "Still waiting... ($i)"
            sleep 2
          done

      - name: Run frontend tests
        working-directory: spotify-analyzer
        run: npm test
